export const ROUTES = {
  home: "/",
  builder: "/builder",
  champions: "/champions",
  championsBuilder: "/champions/builder",
  championsDamage: "/champions/damage",
  championsPresets: "/champions/presets",
  championsPlans: "/champions/plans",
  championsBuilderPlans: "/champions/builder?tab=plans",
  championsCoach: "/champions/coach",
  championsCommunity: "/champions/community",
  pokedex: "/pokedex",
  abilities: "/abilities",
  strategies: "/strategies",
  teamCard: "/team-card",
  profile: "/profile",
  login: "/login",
  register: "/register",
} as const;
