import type {
  MegaDependencyInsight,
  PlanCoachWarning,
  ReadinessSummary,
  ThreatChecklistEntry,
  WeaknessEntry,
} from "@/lib/champions/matchup-coach-analysis";
import type { ChampionsBattlePlan, ChampionsTeam } from "@/types/champions";

export function formatCoachBriefingExport({
  team,
  readiness,
  weaknessMap,
  threatChecklist,
  selectedPlan,
  planWarnings,
  megaInsight,
}: {
  team: ChampionsTeam;
  readiness: ReadinessSummary;
  weaknessMap: WeaknessEntry[];
  threatChecklist: ThreatChecklistEntry[];
  selectedPlan: ChampionsBattlePlan | null;
  planWarnings: PlanCoachWarning[];
  megaInsight: MegaDependencyInsight;
}): string {
  const lines: string[] = [];
  const roster = team.pokemon.filter((slot) => slot.pokemonName.trim().length > 0);

  lines.push(`Champions Matchup Coach — ${team.name || "Untitled team"}`);
  lines.push("=".repeat(48));
  lines.push("");
  lines.push(`Readiness: ${readiness.score}/10 — ${readiness.label}`);
  if (readiness.tags.length > 0) {
    lines.push(`Tags: ${readiness.tags.join(", ")}`);
  }
  lines.push(
    `Roster: ${roster.length}/6 · Plans: ${team.battlePlans.length}${
      selectedPlan ? ` · Analyzing: ${selectedPlan.name}` : " · Full roster"
    }`,
  );
  lines.push("");

  if (readiness.alerts.length > 0) {
    lines.push("Alerts");
    readiness.alerts.forEach((alert) => lines.push(`  • ${alert}`));
    lines.push("");
  }

  const topWeaknesses = weaknessMap.filter((entry) => entry.weak > 0).slice(0, 5);
  if (topWeaknesses.length > 0) {
    lines.push("Top defensive weaknesses");
    topWeaknesses.forEach((entry) => {
      lines.push(`  • ${entry.type}: ${entry.weak} weak, ${entry.resist} resist, ${entry.immune} immune`);
    });
    lines.push("");
  }

  const exposed = threatChecklist.filter((threat) => threat.status === "exposed");
  const risky = threatChecklist.filter((threat) => threat.status === "risky");
  if (exposed.length > 0 || risky.length > 0) {
    lines.push("Threat checklist");
    exposed.forEach((threat) => lines.push(`  ✗ ${threat.label} (exposed)`));
    risky.forEach((threat) => lines.push(`  ! ${threat.label} (risky)`));
    lines.push("");
  }

  if (megaInsight.warnings.length > 0) {
    lines.push("Mega notes");
    megaInsight.warnings.forEach((warning) => lines.push(`  • ${warning}`));
    lines.push("");
  }

  const criticalWarnings = planWarnings.filter((warning) => warning.severity === "critical");
  if (criticalWarnings.length > 0) {
    lines.push("Plan warnings");
    criticalWarnings.forEach((warning) => lines.push(`  • ${warning.message}`));
    lines.push("");
  }

  lines.push("Roster");
  roster.forEach((slot) => {
    const moves = slot.moves.filter(Boolean).join(", ") || "—";
    lines.push(`  ${slot.slot}. ${slot.pokemonName} — ${slot.ability || "—"} @ ${slot.item || "—"}`);
    lines.push(`     ${slot.statAlignment} · SP spe ${slot.sp.spe} · ${moves}`);
  });

  lines.push("");
  lines.push("Generated by Pokemon Team Forge — Champions Matchup Coach");

  return lines.join("\n");
}
